//redux/action/actionTypes
export const SET_USER_TYPE = 'SET_USER_TYPE';


export const SET_SELECTED_DOCTOR_ID = 'SET_SELECTED_DOCTOR_ID';


// actionTypes.js
export const NEW_APPOINTMENT_NOTIFICATION = 'NEW_APPOINTMENT_NOTIFICATION';
export const APPOINTMENT_STATUS_CHANGED = 'APPOINTMENT_STATUS_CHANGED';
export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';
